### ISSUE TITLE
Possible adjustment requirement for Windows friendliness

### ISSUE THREAD

**Issue by cicero44bc** [OverByThere/MapleSyrup#3]
In order to bring the VM up with Vagrant I had to;

vagrant plugin install vagrant_box_version
vagrant plugin install vagrant-triggers

Else vagrant up would return;

There are errors in the configuration of this machine. Please fix
the following errors and try again:

Vagrant:
* Unknown configuration section 'version'.

Not sure if this is normal

**Comment by DanClarke-io** [comment]
This has now been noted, and added to the README as part of installation. Thanks for the report.
